#!/usr/bin/env python3

import sys
import yaml
from pathlib import Path

from config import Config
from labels import Labels
import scanner
import terraform

if len(sys.argv) != 5:
    print("Usage: beautiful-labels <command> <org> <repo> <directory>", file=sys.stderr)
    print("\nValid commands: scan, write-config", file=sys.stderr)
    sys.exit(1)

org = sys.argv[2]
repo = sys.argv[3]
working_dir = sys.argv[4]

config = Config(working_dir, org, repo)
labels = Labels(org, repo)

cmd = sys.argv[1]
if cmd == "scan":
    labels = scanner.scan_labels(config)
    labels.save(config.yaml_filename())
elif cmd == "write-config":
    labels.load(config.yaml_filename())
    terraform.write_terraform_config(labels, config.terraform_filename())
else:
    print("Unknown command '%s'. Exiting." % cmd, file=sys.stderr)
    sys.exit(1)
