#!/usr/bin/env python3
"""Usage:
  beautiful-labels scan ORG REPO --output-file=<filename>
  beautiful-labels create-svg CONFIG_FILE REPO --output-file=<filename> [--label-font-size=<size>]
  beautiful-labels write-config CONFIG_FILE --output-file=<filename>
  beautiful-labels save-backup CONFIG_FILE REPO OUTPUT_DIRECTORY
  beautiful-labels show CONFIG_FILE
  beautiful-labels -h | --help

Commands:
  scan          Scan existing labels of repo and create YAML configuration file
  create-svg    Create picture from YAML configuration with overview of labels
  write-config  Write Terraform configuration from YAML configuration
  save-backup   Save label assignment as backup in a JSON file
  show          Show parsed content of YAML configuration on standard output

Arguments:
  ORG               Name of GitHub organization
  REPO              Name of GitHub repository
  CONFIG_FILE       Path of YAML configuration file
  OUTPUT_DIRECTORY  Path of directory where backup files are written

Options:
  -h, --help                    Show this help
  --label-font-size=<size>      Size of font on labels
  -o, --output-file=<filename>  Name of file where data is written to
"""
from docopt import docopt

import sys
import yaml
from pathlib import Path

from labels import Labels
import scanner
import terraform
import svg
import backup

arguments = docopt(__doc__)

org = arguments["ORG"]
repo_name = arguments["REPO"]
config_file = arguments["CONFIG_FILE"]
output_directory = arguments["OUTPUT_DIRECTORY"]
output_file = arguments["--output-file"]
label_font_size = arguments["--label-font-size"]
if label_font_size == None:
    label_font_size = 14

labels = Labels()

cmd = sys.argv[1]
if cmd == "scan":
    labels = scanner.scan_labels(output_file, org, repo_name)
    labels.save(output_file)
elif cmd == "write-config":
    labels.load(config_file)
    terraform.write_terraform_config(labels, output_file)
elif cmd == "create-svg":
    labels.load(config_file)
    repo = labels.repo(repo_name)
    if not repo:
        sys.exit("Unknown repo '%s'" % repo_name)
    svg.write_svg(labels.org, repo, output_file, label_font_size=label_font_size)
elif cmd == "save-backup":
    labels.load(config_file)
    if not labels.repo(repo_name):
        sys.exit("Unknown repo '%s'" % repo_name)
    backup.save(labels.org, repo_name, output_directory)
elif cmd == "show":
    labels.load(config_file)
    labels.show()
else:
    print("Unknown command '%s'. Exiting." % cmd, file=sys.stderr)
    sys.exit(1)
